site_name: All in one small scale RWD Drift Guide
site_description: All-in-one reference for small-scale RWD RC drift chassis, history, setup and beginner guides.
site_url: https://darol0o5.github.io/Guide/

extra:
  homepage: https://darol0o5.github.io/Guide/
  og_image: https://darol0o5.github.io/Guide/assets/og/default.jpg

  analytics:
    provider: custom

nav:
  - Home: index.md
  - History:
     - How RWD came to small scale drifting: history/how-rwd-came-to-small-scale.md
  - Terminology: terminology/terminology.md
  - Beginner:
      - Choosing Your First Chassis: beginner/firstchassis.md
  - Chassis: chassis/catalogue.md
  - Contribute: contribute/contribute.md
     


theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.tooltips
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
    - stylesheets/extra.css
    - stylesheets/ratings.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2
  - javascripts/ratings.js



markdown_extensions:
    - meta
    - admonition
    - attr_list
    - md_in_html
    - toc:
       permalink: true
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.mark
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg



plugins:
  - search
  
  
